/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xIyE9THYlNO
 */
import { Button } from "@/components/ui/button"

export function ClickPage() {
  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen bg-white p-4">
      <header className="flex items-center justify-center mb-12">
        <SnowflakeIcon className="text-blue-500 w-6 h-6 mr-2" />
        <h1 className="text-lg font-semibold text-gray-700">medium.click</h1>
      </header>
      <main className="flex flex-col items-center">
        <h2 className="text-6xl font-bold text-gray-800 mb-4">12.785</h2>
        <p className="text-2xl text-gray-600 mb-8">VOCÊ JÁ CLICOU HOJE?</p>
        <Button
          className="bg-blue-500 text-white px-6 py-3 rounded shadow hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50">
          CLIQUE AQUI
        </Button>
      </main>
      <footer className="flex justify-between items-center w-full max-w-2xl mt-12">
        <span className="text-sm text-gray-500">CLIQUES TOTAIS 12.785</span>
        <span className="text-sm text-gray-500">SEUS CLIQUES 584</span>
      </footer>
    </div>)
  );
}


function SnowflakeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="2" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="m20 16-4-4 4-4" />
      <path d="m4 8 4 4-4" />
      <path d="m16 4-4 4-4-4" />
      <path d="m8 20 4-4 4" />
    </svg>)
  );
}
